graph TD

  tab1(Papers identified by database searches k = 3113)
  tab1 --> tab2(Papers screened based on title and abstract k = 431)
  tab1 --> tab5(Papers excluded based on title k = 2682)
  tab2 --> tab3(Full text assessed for eligibility k = 128)
  tab2 --> tab6(Papers excluded based on abstract k = 303)
  tab3 --> tab4(Papers included for meta-analysis k = 18)
  tab3 --> tab7(Papers excluded after full text assessed k = 110)
